### ISSUE TITLE
prometheus exporter issues

### ISSUE THREAD

**Issue by ctonur** [devopsfaith/krakend-opencensus#44]
Hi

We have implement prometheus exporter but it does not return any logs  and also ı cant see any things about metric on prometheus.

should the prometheus and krakend be in same namespaces ? 

    "github_com/devopsfaith/krakend-opencensus": {
    		"exporters": {
     			 "prometheus": {
        			"port": 9090,
         			"namespace": "cattle-monitoring-system"

**Comment by krishna-kunderu** [comment]
Hello I have used opencensus metrics exporter to Prometheus in KrakenD API Gateway. 

Added this in extra_config according to KrakenD documentation
`"github_com/devopsfaith/krakend-opencensus": {
      "sample_rate": 100,
      "reporting_period": 1,
      "enabled_layers": {
        "backend": true,
        "router": true,
        "pipe": true
      },
      "exporters": {
        "prometheus": {
          "port": 9091,
          "namespace": "krakend",
          "tag_host": true,
          "tag_path": true,
          "tag_method": true,
          "tag_statuscode": true
        }
      }
    },`

And my prometheus yml is as below

`global:
  scrape_interval:     15s
  evaluation_interval: 15s

rule_files:
# - "first.rules"
# - "second.rules"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['127.0.0.1:9090']`

I deployed prometheus into docker image FROM prom/prometheus

I can access http://localhost:9090/metrics but it just shows prometheus general metrics. I don't see any KrakenD metrics related to backed/router/proxy though enabled them in krakend.json extra_config.

Just to let you know I am using custom http server plugin with GO 1.16.4 which does some business logic to handle the requests of KrakenD acting as a router. This plugin is needed to transform JSON to SOAP. Not sure if I have to do anything in my handler to catpure the prometheus metrics?

Any support on this would be much appreciated.

**Comment by kpacha** [comment]
@krishna-kunderu your prometheus is the one responsible for scrapping the metrics. add a new entry at your prometheus.yml letting it know where to look for the krakend instance

```
global:
  scrape_interval:     15s
  evaluation_interval: 15s

rule_files:
  # - "first.rules"
  # - "second.rules"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'krakend'
    static_configs:
      - targets: ['krakend-hostname:9091']
```
