### ISSUE TITLE
Krakend Metrics are not able to export into Prometheus

### ISSUE THREAD

**Issue by krishna-kunderu** [devopsfaith/krakend-opencensus#61]
![image](https://user-images.githubusercontent.com/99324244/157088339-96313f2e-7f00-4da0-a04e-daa00aa940b9.png)
I updated with the krakend 9091 in the prometheus yml. I see the target in the graph targets of prometheus, but prometheus somehow not able to connect to the same on Krakend. Both are running on localhost on different containers of docker.

Tried accessing __stats of Krakend and I can see the stats generated in Krakend, but some how metrics are not getting exported to Prometheus. 

There was closed ticket #44 , which I have followed to get this configured in my local.

```
global:
  scrape_interval:     15s
  evaluation_interval: 15s

rule_files:
  # - "first.rules"
  # - "second.rules"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'krakend'
    static_configs:
      - targets: ['localhost:9091']
```

**Comment by kpacha** [comment]
please, check the docker documentation regarding networking (https://docs.docker.com/network/). for a prometheus instance -running in a docker container- `localhost` resolves to the container itself. that's why, in my response at the linked issue, I wrote `'krakend-hostname:9091'`.

the host and the containers are not using the same network adapter, unless required by you: change your container network or link the krakend container to the prometheus one (and use the hostname in your `prometheus.yml` file).

**Comment by krishna-kunderu** [comment]
@kpacha 
Thanks for that, I have tried the network link and  mentioned the krakend host. I could able to ping krakend in prometheus container with no issues. But for some reason prometheus is not able to get any connection on the port 9091, though I mentioned about 9091 in krakend config as below. Still trying to figure out where its going wrong. I tried even exposing the port 9091 in docker-compose, but still prometheus can't listen to port 9091. though host krakend is accessible from the prometheus container.
```
    "telemetry/opencensus": {
      "exporters": {
        "krakendapigw": {
          "port": 9091,
          "namespace": "krakend",
          "tag_host": false,
          "tag_path": true,
          "tag_method": true,
          "tag_statuscode": true
        }
      }
    },

```
prometheus.yml

```
global:
  scrape_interval:     15s
  evaluation_interval: 15s

rule_files:
# - "first.rules"
# - "second.rules"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'krakendapigw'
    static_configs:
      - targets: ['krakend:9091']
```

![image](https://user-images.githubusercontent.com/99324244/157214697-b7513366-e38f-4619-8e04-befabbca02d3.png)
